services:
    directus:
        image: directus/directus:latest
        ports:
            - "8055:8055"
        environment:
            KEY: "your-secret-key"
            SECRET: "another-secret"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "admin"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/data/data.db"
            CORS_ENABLED: "true"
            CORS_ORIGIN: "http://localhost:5173"

        volumes:
            - ./directus/data:/data

    frontend:
        build: ./frontend
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules

        depends_on:
            - directus
        command: ["npm", "run", "dev"]
